import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';

process.env.LUMEN_DB_PATH=':memory:';
process.env.LUMEN_DEMO='1';
process.env.NODE_ENV='test';
const {buildHandler}=await import('../src/server.mjs');
const server=createServer(buildHandler());
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const host='http://127.0.0.1:'+server.address().port;
test.after(()=>new Promise(resolve=>server.close(resolve)));

test('health, static PWA shell, and PNG icons are served',async()=>{
  const health=await fetch(host+'/api/health');
  assert.deepEqual(await health.json(),{status:'ok',db:true});
  const html=await fetch(host+'/');
  assert.equal(html.status,200);
  assert.ok((await html.text()).includes('LUMEN'));
  const icon=await fetch(host+'/icons/icon-192.png');
  assert.equal(icon.status,200);
  const bytes=new Uint8Array(await icon.arrayBuffer());
  assert.deepEqual(Array.from(bytes.slice(0,8)),[137,80,78,71,13,10,26,10]);
  const manifest=await fetch(host+'/manifest.webmanifest');
  assert.equal((await manifest.json()).display,'standalone');
});
test('HTTP auth, same-origin, CSRF, and patron authorisation',async()=>{
  const badOrigin=await fetch(host+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://evil.example'},body:JSON.stringify({email:'student@lumen.local',password:'Demo1234!'})});
  assert.equal(badOrigin.status,403);
  const login=await fetch(host+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:host},body:JSON.stringify({email:'student@lumen.local',password:'Demo1234!'})});
  assert.equal(login.status,200);
  const data=await login.json(),cookie=login.headers.get('set-cookie').split(';')[0];
  assert.equal(data.user.role,'student');
  const books=await (await fetch(host+'/api/books')).json(),book=books[0];
  const base={method:'POST',headers:{'Content-Type':'application/json',Origin:host,Cookie:cookie}};
  const badCsrf=await fetch(host+'/api/holds',{...base,body:JSON.stringify({bookId:book.id})});
  assert.equal(badCsrf.status,403);
  const goodHeaders={...base.headers,'X-CSRF-Token':data.csrf};
  const hold=await fetch(host+'/api/holds',{...base,headers:goodHeaders,body:JSON.stringify({bookId:book.id})});
  assert.equal(hold.status,201);
  const duplicate=await fetch(host+'/api/holds',{...base,headers:goodHeaders,body:JSON.stringify({bookId:book.id})});
  assert.equal(duplicate.status,409);
  const forbidden=await fetch(host+'/api/suggestions',{...base,headers:goodHeaders,body:JSON.stringify({title:'X',author:'Y',reason:'Z'})});
  assert.equal(forbidden.status,403);
  const mine=await fetch(host+'/api/holds',{headers:{Cookie:cookie}});
  assert.equal((await mine.json()).length,1);
  const logout=await fetch(host+'/api/logout',{...base,headers:goodHeaders,body:'{}'});
  assert.equal(logout.status,200);
  const blocked=await fetch(host+'/api/holds',{headers:{Cookie:cookie}});
  assert.equal(blocked.status,401);
});
